name: SecureSafe CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest pytest-cov

      - name: Check Code Formatting with Black
        run: python -m black --check $(git ls-files '*.py')

      - name: Lint with Flake8
        run: flake8 --ignore=E501,W503 .

      - name: Run Unit Tests with Coverage
        run: pytest --cov=secure_safe --cov-report=xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Notify on Failure
        if: failure()
        run: echo "🚨 Build failed! Please check the logs."